from cryptsenal.caesar import Caesar
import pytest


def test_encrypt():
    plainText = "FRIENDSROMANSCOUNTRYMENLENDMEYOUREARSICOMETOBURYCAESARNOTTOPRAISEHIM"
    tests = ["AMDZIYNMJHVINXJPIOMTHZIGZIYHZTJPMZVMNDXJHZOJWPMTXVZNVMIJOOJKMVDNZCDH",
             "VHYUDTIHECQDISEKDJHOCUDBUDTCUOEKHUQHIYSECUJERKHOSQUIQHDEJJEFHQYIUXYC",
             "KWNJSIXWTRFSXHTZSYWDRJSQJSIRJDTZWJFWXNHTRJYTGZWDHFJXFWSTYYTUWFNXJMNR",
             "QCTPYODCZXLYDNZFYECJXPYWPYOXPJZFCPLCDTNZXPEZMFCJNLPDLCYZEEZACLTDPSTX",
             "OARNWMBAXVJWBLXDWCAHVNWUNWMVNHXDANJABRLXVNCXKDAHLJNBJAWXCCXYAJRBNQRV"]
    for test, key in zip(tests, (21, 16, 5, 11, 9)):
        assert Caesar(plainText, key).encrypt() == test


def test_decrypt():
    plainText = "FRIENDSROMANSCOUNTRYMENLENDMEYOUREARSICOMETOBURYCAESARNOTTOPRAISEHIM"
    cipherTexts = ["NZQMVLAZWUIVAKWCVBZGUMVTMVLUMGWCZMIZAQKWUMBWJCZGKIMAIZVWBBWXZIQAMPQU",
                   "MYPLUKZYVTHUZJVBUAYFTLUSLUKTLFVBYLHYZPJVTLAVIBYFJHLZHYUVAAVWYHPZLOPT",
                   "GSJFOETSPNBOTDPVOUSZNFOMFOENFZPVSFBSTJDPNFUPCVSZDBFTBSOPUUPQSBJTFIJN",
                   "DPGCLBQPMKYLQAMSLRPWKCLJCLBKCWMSPCYPQGAMKCRMZSPWAYCQYPLMRRMNPYGQCFGK",
                   "EQHDMCRQNLZMRBNTMSQXLDMKDMCLDXNTQDZQRHBNLDSNATQXBZDRZQMNSSNOQZHRDGHL"]
    for cipherText, key in zip(cipherTexts, (8, 7, 1, 24, 25)):
        assert Caesar(
            cipherText, key).decrypt() == plainText
