"""
Modules:
    ['affine.py',
    'caesar.py',
    'detect_english.py',
    'morse.py',
    'number_system.py',
    'one_time_pad.py',
    'simple_sub.py',
    'tranposition.py',
    'vigenere.py']
"""